### PR TITLE
QFF Layer and Fixed Map Image Size

### LINKED ISSUE #41: Update layer url
Please attempt to use this map service (http://webmaps.geology.utah.gov/arcgis/rest/services/Hazards/quaternary_faults/MapServer/0) hosted on our UGS server versus the agol hosted featurelayer. This is desired because of issues with symbology

https://github.com/agrc/ugs-hazards/blob/d15cbf6d747640b290f46eb7dfaf269f7cc5772f/src/config.js#L44

### PR DESCRIPTION
**Pull request by stdavis**
The PR makes attempts to close #41 (switch to map image layer for QFF) & #46 (fixed map widths).

For #41, it turned into a bit of a mess. I wonder if we should just tell them that it's not going to work with map image layers. I did get it close but had to add a lot of exception code around the map image layer that feels pretty hacky. The legends still don't work. I'm pretty sure that it's because they are symbolizing on a field that we aren't expecting.

https://github.com/agrc/ugs-hazards/commit/4af57c65f7005d35d3d39a7253a8e4354a758eab was a bug that I found when I drew an AOI that contained a lot of aerial imagery points.

I also added a map with sketch tools to the demo page to allow for drawing AOIs rather than having to get the JSON code from somewhere else and copy/paste.

For #46, I think that the scales are now pretty close to correct. Here was my sanity check:
image

I've pushed this to test so that people that check it out.

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -173,40 +173,42 @@ export default props => {
...
-        </OtherDataPage>
-        <OtherDataPage {...otherDataMap['Aerial Photography and Imagery']} mapKey={config.mapKeys.aerials} id="aerial-photography">
-          {aerialFeatures.map((feature, index) => <AerialFeature key={index} {...feature} />)}
-        </OtherDataPage>
-      </HazardMap>
-      <div className="header page-break">
-        <h1>OTHER GEOLOGIC HAZARD RESOURCES</h1>
-        <p dangerouslySetInnerHTML={{__html: reportTextMap.OtherGeologicHazardResources}}
-          title={config.notProd && 'ReportTextTable.Text(OtherGeologicHazardResources)'}></p>
+      <div className="app--container">
```
Comment (steveoh) [inline src/App.js]: since you are learning bems i thought i would mention that -- are for modifiers and __ are for elements. No need to update, just an FYI

Comment (stdavis) [reply src/App.js]: Thanks for the reminder...
